if(NOT DEFINED RTT_SCONS_CONFIG_FILE AND DEFINED ENV{RTT_SCONS_CONFIG_FILE})
    set(RTT_SCONS_CONFIG_FILE "$ENV{RTT_SCONS_CONFIG_FILE}")
endif()

if(NOT DEFINED RTT_SCONS_CONFIG_FILE)
    message(FATAL_ERROR "RTT_SCONS_CONFIG_FILE must point to the configuration generated by SCons")
endif()

get_filename_component(RTT_SCONS_CONFIG_FILE "${RTT_SCONS_CONFIG_FILE}" ABSOLUTE)
set(
    RTT_SCONS_CONFIG_FILE
    "${RTT_SCONS_CONFIG_FILE}"
    CACHE FILEPATH
    "RT-Thread SCons generated CMake configuration"
    FORCE
)

# Preserve the generated SCons configuration when CMake creates a nested
# project to probe the compiler with try_compile().
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES RTT_SCONS_CONFIG_FILE)
list(REMOVE_DUPLICATES CMAKE_TRY_COMPILE_PLATFORM_VARIABLES)

if(NOT EXISTS "${RTT_SCONS_CONFIG_FILE}")
    message(FATAL_ERROR "RT-Thread SCons configuration not found: ${RTT_SCONS_CONFIG_FILE}")
endif()

include("${RTT_SCONS_CONFIG_FILE}")

foreach(required_variable
        RTT_SCONS_C_COMPILER
        RTT_SCONS_CXX_COMPILER
        RTT_SCONS_AR
        RTT_SCONS_SYSTEM_PROCESSOR)
    if(NOT DEFINED ${required_variable} OR "${${required_variable}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${required_variable} in ${RTT_SCONS_CONFIG_FILE}")
    endif()
endforeach()

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR "${RTT_SCONS_SYSTEM_PROCESSOR}")
set(CMAKE_CROSSCOMPILING ON)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER "${RTT_SCONS_C_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${RTT_SCONS_CXX_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${RTT_SCONS_AR}" CACHE FILEPATH "" FORCE)

# rosidl_default_generators scans every package registered in the host ament
# index. Keep host build tools available while excluding generators and type
# supports that cannot be linked into the RT-Thread C-only static library.
foreach(disabled_package IN ITEMS
        rosidl_generator_cpp
        rosidl_generator_py
        rosidl_typesupport_cpp
        rosidl_typesupport_fastrtps_c
        rosidl_typesupport_fastrtps_cpp
        rosidl_typesupport_introspection_c
        rosidl_typesupport_introspection_cpp
        rosidl_typesupport_microxrcedds_cpp)
    set(
        CMAKE_DISABLE_FIND_PACKAGE_${disabled_package}
        ON
        CACHE BOOL
        "Disabled for the micro-ROS RT-Thread static library"
        FORCE
    )
endforeach()

# Select the MCU RMW explicitly so the host ROS installation cannot supply its
# default Fast DDS implementation. A static library cannot select an RMW at
# runtime through dlopen().
set(
    RMW_IMPLEMENTATION
    "rmw_microxrcedds"
    CACHE STRING
    "RMW implementation for the micro-ROS RT-Thread static library"
    FORCE
)
set(
    RMW_IMPLEMENTATION_DISABLE_RUNTIME_SELECTION
    ON
    CACHE BOOL
    "Disable dynamic RMW loading for the RT-Thread static library"
    FORCE
)

# SCons CPPPATH is serialized as -I flags alongside its architecture,
# diagnostics and optimization flags. Clear CMake's build-type defaults so
# Release does not silently replace those choices.
set(CMAKE_C_FLAGS "${RTT_SCONS_C_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${RTT_SCONS_CXX_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE "" CACHE STRING "" FORCE)

set(__BIG_ENDIAN__ 0)
